force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <label>Weather Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/CityName__c.field-meta.xml
<CustomField>
    <fullName>CityName__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/TempFeelsLike__c.field-meta.xml
<CustomField>
    <fullName>TempFeelsLike__c</fullName>
    <label>Temp Feels Like</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/WeatherDescription__c.field-meta.xml
<CustomField>
    <fullName>WeatherDescription__c</fullName>
    <label>Weather Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/WindSpeed__c.field-meta.xml
<CustomField>
    <fullName>WindSpeed__c</fullName>
    <label>Wind Speed</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather_Setting__c/Weather_Setting__c.object-meta.xml
<CustomObject>
    <label>Weather Setting</label>
    <nameField>
        <label>Weather Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeatherSetting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_Setting__c/fields/CityName__c.field-meta.xml
<CustomField>
    <fullName>CityName__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherService.cls
public with sharing class WeatherService {
    
    public static void updateWeather(){
        List<Weather_Setting__c> weatherSettingsList = [SELECT Id, CityName__c, Language__c FROM Weather_Setting__c];
        if(weatherSettingsList.isEmpty() || weatherSettingsList.size() > 1){
            throw new WeatherException('Weather setting size is inappropriate. Size = ' + weatherSettingsList.size());
        }

        HttpResponse resp = WeatherApi.getWeather(weatherSettingsList[0].CityName__c);
        if(resp.getStatusCode() != 200){
            throw new WeatherException('Http request error. Response StatusCode = ' + resp.getStatusCode());
        }
        
        WeatherAPIWrappers.GetWeatherResponse respWrapper = 
            (WeatherAPIWrappers.GetWeatherResponse) System.JSON.deserialize(resp.getBody(), WeatherAPIWrappers.GetWeatherResponse.class);

        Weather__c weatherToInsert = new Weather__c();
        weatherToInsert.Name = String.format(System.Label.Weather_Name, new List<Object> {respWrapper.name});
        weatherToInsert.CityName__c = respWrapper.name;
        weatherToInsert.Humidity__c = respWrapper.main.humidity;
        weatherToInsert.Pressure__c = respWrapper.main.pressure;
        weatherToInsert.TempFeelsLike__c = respWrapper.main.feels_like;
        weatherToInsert.Temperature__c = respWrapper.main.temp;
        weatherToInsert.WeatherDescription__c = respWrapper.weather[0].description;
        weatherToInsert.WindSpeed__c = respWrapper.wind.speed;
        weatherToInsert.Location__longitude__s = respWrapper.coord.lon;
        weatherToInsert.Location__latitude__s = respWrapper.coord.lat;
        weatherToInsert.Date__c = DateTime.newInstance(respWrapper.dt*1000).date();

        insert weatherToInsert;
    }

    public class WeatherException extends Exception{}
}