force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <label>Weather Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/CityName__c.field-meta.xml
<CustomField>
    <fullName>CityName__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/TempFeelsLike__c.field-meta.xml
<CustomField>
    <fullName>TempFeelsLike__c</fullName>
    <label>Temp Feels Like</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/WeatherDescription__c.field-meta.xml
<CustomField>
    <fullName>WeatherDescription__c</fullName>
    <label>Weather Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/WindSpeed__c.field-meta.xml
<CustomField>
    <fullName>WindSpeed__c</fullName>
    <label>Wind Speed</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomWeatherViewController.cls
public with sharing class CustomWeatherViewController {
    
    @AuraEnabled
    public static List<Weather__c> getWeather(){
        List<Weather__c> weatherList = [
            SELECT Id, 
                CityName__c, 
                Date__c, 
                Humidity__c, 
                Location__c, 
                Pressure__c, 
                TempFeelsLike__c, 
                Temperature__c, 
                WeatherDescription__c, 
                WindSpeed__c 
            FROM Weather__c];
        return weatherList;
    }
}