force-app/main/default/objects/Case_Event__e/Case_Event__e.object-meta.xml
<CustomObject>
    <label>Case Event</label>
    <pluralLabel>Case Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Event__e/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Event__e/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseService.cls
public with sharing class CaseService {
    @testVisible private static List<Case_Event__e> listCaseEvents = new List<Case_Event__e>();

    public static void sendEventsOnCaseChange(List<Case> listCasesNew, Map<Id, Case> mapCasesOld){
        for (Case newCase : listCasesNew) {

            if (newCase.Status != mapCasesOld.get(newCase.Id).Status && newCase.Status == 'In Progress') {
                Case_Event__e newCaseEvent = new Case_Event__e();
                newCaseEvent.Case_Id__c = newCase.Id;
                newCaseEvent.User_Id__c = UserInfo.getUserId();
                listCaseEvents.add(newCaseEvent);
            }
        }
        
        List<Database.SaveResult> eventPublishResults = Eventbus.publish(listCaseEvents);

        for (Database.SaveResult saveRes : eventPublishResults) {

            if (!saveRes.isSuccess()){
                throw new EventPublishException('Event publish errors. Error - ' + saveRes.getErrors());
            }
        }
    }

    public class EventPublishException extends Exception{}
}